// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9bdtUGvJToVNi1O68y-jUEWa4Oe8XAdo',
    appId: '1:993406920368:web:ee279b8789370c071fbd75',
    messagingSenderId: '993406920368',
    projectId: 'pjspotify01',
    authDomain: 'pjspotify01.firebaseapp.com',
    storageBucket: 'pjspotify01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7dqlqrroX0FS1lcEmzGREHp2b0ZqAR0c',
    appId: '1:993406920368:android:8117fc6efa5238361fbd75',
    messagingSenderId: '993406920368',
    projectId: 'pjspotify01',
    storageBucket: 'pjspotify01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyU-OKVacWAX-n6Lk8W5Y25UmYl8IseI',
    appId: '1:993406920368:ios:b5a271f33beb03f81fbd75',
    messagingSenderId: '993406920368',
    projectId: 'pjspotify01',
    storageBucket: 'pjspotify01.appspot.com',
    androidClientId: '993406920368-ftrhn2m2re4c98o4d13koriamaqcleq0.apps.googleusercontent.com',
    iosClientId: '993406920368-b3mkih4lmmd3io2mcprp1i8pr5ijjrnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpyU-OKVacWAX-n6Lk8W5Y25UmYl8IseI',
    appId: '1:993406920368:ios:b5a271f33beb03f81fbd75',
    messagingSenderId: '993406920368',
    projectId: 'pjspotify01',
    storageBucket: 'pjspotify01.appspot.com',
    androidClientId: '993406920368-ftrhn2m2re4c98o4d13koriamaqcleq0.apps.googleusercontent.com',
    iosClientId: '993406920368-b3mkih4lmmd3io2mcprp1i8pr5ijjrnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9bdtUGvJToVNi1O68y-jUEWa4Oe8XAdo',
    appId: '1:993406920368:web:19f6b2d593214a711fbd75',
    messagingSenderId: '993406920368',
    projectId: 'pjspotify01',
    authDomain: 'pjspotify01.firebaseapp.com',
    storageBucket: 'pjspotify01.appspot.com',
  );

}